#pragma config(Sensor, S1,     Touch,          sensorEV3_Touch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	motor[motorB] = 50;
	motor[motorC] = 50;
	while(SensorValue[Touch] == 0) {}
	motor[motorB] = 50;
	motor[motorC] = 50;
}
