#pragma config(Sensor, S1,     Touch,          sensorEV3_Touch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(ture)
		{
			while(SensorValue[Touch] == 0) {}
			while(SensorValue[Touch] == 1) {}
			motor[motorB] = 50;
			motor[motorC] = 50;

			while(SensorValue[Touch] == 0) {}
			while(SensorValue[Touch] == 1) {}
			motor[motorB] = 0;
			motor[motorC] = 0;
		}
}
