#pragma config(Sensor, S1,     Touch,          sensorEV3_Touch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(ture)
	{
		motor[motorB] = 50;
		motor[motorC] = 50;
		while(SensorValue[Touch] == 0) {}

		motor[motorB] = -30;
		motor[motorC] = -30;
		wait1Msec(2000);

		moveMotorTarget(motorC,360,50);
	}
}
