#pragma config(Sensor, S4,     sonar,          sensorEV3_Ultrasonic)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)(SensorValue[sonar]<10)
	{
		motor[motorB] = 30;
		motor[motorC] = 30;
	}
	motor[motorB] = -30;
	motor[motorC] = -30;
	wait1Msec(2000);

	motor[motorB] = -50;
	motor[motorC] = 50;
	wait1Msec(1000);
}
