#pragma config(Sensor, S4,     sonar,          sensorEV3_Ultrasonic)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	motor[motorB] = 50;
	motor[motorC] = 50;
	while{SensorValue[sonar]>20} {}
	motor[motorB] = 0;
	motor[motorC] = 0;
}
