#pragma config(Sensor, S2,     Gyro,           sensorEV3_Gyro)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int FV = SensorValue[Gyro];
	while(1)
	{
		motor[motorB] = 30-(SensorValue[Gyro]-FV);
		motor[motorC] = 30;
	}
}
