#pragma config(Sensor, S2,     Gyro,           sensorEV3_Gyro)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(SensorValue[Gyro]<=360)
	{
		motor[motorB] = 50;
		motor[motorC] = -50;
	}
}
